console.log(0 == false); // true
console.log(0 === false); // false
console.log(1 == "1"); // true
console.log(1 === "1"); // false
console.log(null == undefined); // true
console.log(null === undefined); // false
console.log("0" == false); // true
console.log("0" === false); // false
console.log(NaN == NaN); // false
console.log(NaN === NaN); // false
console.log([] == []); // false
console.log([] === []); // false
console.log({} == {}); // false
console.log({} === {}); // false
